In [112]:
#Practice Problem 1:
#You are working with a 2D NumPy array of integers, where each element represents the elevation of a corresponding area
#on a map. You need to transpose this array to view the landscape from a different perspective.
#Task:
#Create a 2D NumPy array: This array should represent a grid of elevations, with each integer value ranging from 1 to 1000. 
#The shape of the array should be (5, 5).
#Transpose the Array: Write a function that takes in the 2D NumPy array and returns a new array that is a transposition 
#of the original array. The transposition should be done using NumPy functionalities.
#Display the Original and Transposed Array: Finally, print both the original and the transposed array to the console.

In [113]:
#Import NumPy module, as np so future commands can be more concise:
import numpy as np

#Use the np.array() command to build a 5x5 array with arbitrary values ranging from 1 to 1000
MAP=np.array([[100,250,500,750,900],[50,150,350,600,800],[75,175,275,375,475],[100,200,300,400,500],[1000,900,800,700,600]])

#Use a new variable and the .transpose() function to "flip" the orientation of the array
MAP_transpose = MAP.transpose()

#Show results
print(MAP,'\n')
print(MAP_transpose)

[[ 100  250  500  750  900]
 [  50  150  350  600  800]
 [  75  175  275  375  475]
 [ 100  200  300  400  500]
 [1000  900  800  700  600]] 

[[ 100   50   75  100 1000]
 [ 250  150  175  200  900]
 [ 500  350  275  300  800]
 [ 750  600  375  400  700]
 [ 900  800  475  500  600]]


In [114]:
#Note the "75" row in the middle row in the first array is now a column in the second array. The 900 in the top right
#moves to the bottom left. The 1000 in the bottom left moves to the top right.

In [115]:
#Practice Problem 2:
#You have been given temperature data recorded in a city over a week. The data is stored in a 2D NumPy array, 
#where each row represents a day, and each column represents an hourly temperature reading in Celsius.
#Task:
#Initialize the Temperature Data Array: Create a 2D NumPy array with 7 rows (for 7 days) and 24 columns (for 24 hours). 
#Fill this array with random integers representing the temperature readings between 15 and 35 degrees Celsius.
#Extract Morning Temperatures: Write a function that takes in the temperature data array and returns a new array 
#containing only the temperature readings from 6 AM to 9 AM for every day.
#Calculate Average Morning Temperature: Write a function to calculate the average morning temperature over the week
#using the sliced array from the previous step.
#Display Results: Print the extracted morning temperatures and the average morning temperature to the console.

In [116]:
#First lets generate our set of temperatures

#Specify temperature range and dimensions of the array
low_temp = 15
high_temp = 35
temp_array_shape = (7, 24)

#Use the NP randomint function to generate random values based on our specifications
temp_array = np.random.randint(low_temp,high_temp,size=temp_array_shape)
print('Random Temperatures for each hour throughout the week:\n',temp_array,'\n')

#Specify morning hours

morning_temp_array=temp_array[:,[6,7,8,9]]
print('Morning temperatures:\n',morning_temp_array)

#Calculate average temp
average_morning_temp_array = np.mean(morning_temp_array)
print('The average morning temperature is:',average_morning_temp_array)

Random Temperatures for each hour throughout the week:
 [[21 18 21 20 31 22 34 33 34 34 30 17 28 24 32 29 27 21 27 28 26 15 26 16]
 [20 15 22 15 33 22 34 33 21 26 26 21 30 30 29 25 28 31 28 19 18 32 15 23]
 [30 20 33 32 16 16 22 18 31 24 30 32 31 21 28 31 20 31 25 17 22 33 24 29]
 [25 18 29 16 30 22 34 31 23 32 30 20 29 18 21 32 18 20 19 16 33 23 25 27]
 [15 25 23 26 30 22 30 30 30 19 24 30 31 17 28 21 16 22 30 20 20 19 28 16]
 [19 20 25 31 15 22 28 29 15 30 21 16 24 28 20 28 29 26 23 32 17 26 15 18]
 [22 21 31 26 26 25 33 18 24 18 18 30 32 27 22 31 28 25 28 27 34 24 18 15]] 

Morning temperatures:
 [[34 33 34 34]
 [34 33 21 26]
 [22 18 31 24]
 [34 31 23 32]
 [30 30 30 19]
 [28 29 15 30]
 [33 18 24 18]]
The average morning temperature is: 27.428571428571427


In [117]:
#Practice Problem 3:
#Imagine you are analyzing a dataset representing the ages and heights of a group of people. 
#You are interested in filtering out the data to focus on specific age groups and height ranges.
#Task:
#Create Age and Height Arrays: Generate two 1D NumPy arrays – one representing the ages of 100 people 
#(integer values between 18 and 60) and the other representing the corresponding heights in centimeters 
#(float values between 150.0 and 200.0).
#Filter Data Using Boolean Indexing: Use boolean indexing to filter the arrays and obtain the heights of people who are:
#Between 25 and 35 years old, inclusive.
#Taller than 170 cm.
#Calculate Average Height: After filtering, calculate the average height of the people who meet the above criteria.
#Output: Display the filtered heights and their average.

In [118]:
#Define row count for each vector
size_a = (100)
size_h = (100)

#Set range for random values to be generated within vectors
min_a = 18
max_a = 60
min_h = 150.0
max_h = 200.0

#Run separate random functions for integers and floats to produce two different arrays
column_a = np.random.randint(min_a,max_a,size_a)
column_h = np.random.uniform(min_h,max_h,size_h)

#Merge the arrays into a 2x100 matrix
array_ah = np.column_stack((column_a,column_h))



#Set filter criteria
filter_a_min = 25
filter_a_max = 35

#Create new array based on filter criteria, note the >= and <= to be inclusive
filtered_array = array_ah[(array_ah[:, 0] >= filter_a_min) & (array_ah[:, 0] <= filter_a_max)]

#Create a vector based on filtered matrix array
filtered_h = filtered_array[:, 1]

#Calculate mean of the filtered vector
mean_filtered_h = np.mean(filtered_h)

#Show results
print('The whole data set is:\n',array_ah)
print('The data set filtered to only ages between 25 and 35 inclusive is:\n',filtered_array)
print('The mean height of people in the dataset with ages between 25 and 35 is:\n',mean_filtered_h)

The whole data set is:
 [[ 52.         192.26431196]
 [ 40.         188.14973126]
 [ 47.         185.53979879]
 [ 58.         168.61593199]
 [ 29.         191.32623579]
 [ 30.         186.49137992]
 [ 32.         198.32332714]
 [ 22.         180.18979001]
 [ 19.         193.8583275 ]
 [ 43.         188.53435525]
 [ 38.         152.27222169]
 [ 22.         150.34477337]
 [ 33.         158.4131498 ]
 [ 41.         177.59315855]
 [ 29.         189.59105652]
 [ 41.         195.12873004]
 [ 50.         162.52632866]
 [ 35.         193.38613456]
 [ 21.         159.1341907 ]
 [ 24.         157.3849172 ]
 [ 30.         194.6880061 ]
 [ 31.         150.93251254]
 [ 54.         175.21381028]
 [ 28.         165.21171063]
 [ 59.         198.66276365]
 [ 54.         175.9524545 ]
 [ 38.         154.4967618 ]
 [ 31.         192.33518151]
 [ 54.         187.92089702]
 [ 53.         176.93965074]
 [ 36.         180.65017456]
 [ 29.         197.28925616]
 [ 21.         192.67448473]
 [ 39.         167.

In [119]:
#For this practice problem, I'm going to use a dataset I've used in prior assignments with information on homesales.
#I have taken ChatGPT's practice question and reworded it to be appriopriate for my dataset.
#Practice Problem 4:
#You have been provided a CSV file named "kc_house_data.csv" containing information about homesales. 
#The dataset includes the 21 columns with information on approximately 20,000 homesales.
#Task:
#Load the CSV File: Import the "kc_house_data.csv" file into a Pandas DataFrame.
#Display Specific Rows: Use indexing to display the rows corresponding to the 1st, 5th, and 10th homes in the dataset.
#Display Specific Columns: Show the saleprice and square feet columns for the 3rd, 7th, and 15th sales in the dataset.
#Conditional Display: Display the details of homes with a saleprice above $4M and square footage is above 6000.
#Output: The output should be the displayed rows and columns based on the indexing and condition specified.

In [120]:
#Open the Pandas module
import pandas as pd

#Establish connection to source data
file_path = "C:\\Users\\tejer\\kc_house_data.csv"

#Read CSV file and convert to Pandas dataframe
df = pd.read_csv(file_path)

#View specific rows
print('The 1st, 5th, and 10th rows are as follows:\n')
print(df.loc[[1,5,10]])

#Cool, we can see all 21 columns.

#Let's look at just two columns for specific rows of interest using the loc function:
rows_interest = [3,7,15]
price_sqft = ['price','sqft_lot']

#View results
print('The price and square footage of the lot of the 3rd, 7th, and 15th rows are:\n')
print(df.loc[rows_interest,price_sqft])

#Now let's view all data for observations that meet two criteria:
min_price = 4000000
min_sqft = 6000

#Establish another dataframe equal to the prior dataframe that meets the specified criteria
filtered_df = df[(df['price'] > min_price) & (df['sqft_lot'] > min_sqft)]

#View results
print('The data on houses with a sale price above',min_price,'and a lot square footage of',min_sqft,'are:\n')
print(filtered_df)


The 1st, 5th, and 10th rows are as follows:

            id             date      price  bedrooms  bathrooms  sqft_living  \
1   6414100192  20141209T000000   538000.0         3       2.25         2570   
5   7237550310  20140512T000000  1225000.0         4       4.50         5420   
10  1736800520  20150403T000000   662500.0         3       2.50         3560   

    sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
1       7242     2.0           0     0  ...      7        2170            400   
5     101930     1.0           0     0  ...     11        3890           1530   
10      9796     1.0           0     0  ...      8        1860           1700   

    yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
1       1951          1991    98125  47.7210 -122.319           1690   
5       2001             0    98053  47.6561 -122.005           4760   
10      1965             0    98007  47.6007 -122.145           2210   

    sqft_lot15  
1  

In [121]:
#Practice Probem #5:
#You have a DataFrame loaded with home sales data, including details like date, price, bedrooms, bathrooms, square feet, and year built. 
#Your goal is to analyze this data by sorting it in various ways to gain insights into the home sales market.
#Task:
#Sort by Price: Sort the entire DataFrame based on the price column in descending order and 
#display the top 10 most expensive home sales.
#Sort by Date and Price: Sort the DataFrame first by date in ascending order and then by price in descending order. 
#Display the top 5 results.
#Sort by Number of Bedrooms and Bathrooms: Sort the DataFrame based on the bedrooms column in ascending order and 
#then by bathrooms in descending order. Display the first 10 results.
#Filter and Sort: Filter the DataFrame to include only homes built after the year 2000. 
#Then, sort this filtered data by square feet in descending order and display the top 5 largest homes built 
#after the year 2000.

In [122]:
#Sort by price

#Define sort column
sort_column = 'price'

#Define new dataframe with price sorted in descending order 
sorted_byprice_df = df.sort_values(by=sort_column, ascending=False)

#Display top 10 results
print(sorted_byprice_df.head(10))

              id             date      price  bedrooms  bathrooms  \
7252  6762700020  20141013T000000  7700000.0         6       8.00   
3914  9808700762  20140611T000000  7062500.0         5       4.50   
9254  9208900037  20140919T000000  6885000.0         6       7.75   
4411  2470100110  20140804T000000  5570000.0         5       5.75   
1448  8907500070  20150413T000000  5350000.0         5       5.00   
1315  7558700030  20150413T000000  5300000.0         6       6.00   
1164  1247600105  20141020T000000  5110800.0         5       5.25   
8092  1924059029  20140617T000000  4668000.0         5       6.75   
2626  7738500731  20140815T000000  4500000.0         5       5.50   
8638  3835500195  20140618T000000  4489000.0         4       3.00   

      sqft_living  sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
7252        12050     27600     2.5           0     3  ...     13        8570   
3914        10040     37325     2.0           1     2  ...     11        7680 

In [123]:
#Sort by date and time:

#Convert date to datetime variable for better visibility

df['date'] = pd.to_datetime(df['date'], format='%Y%m%dT%H%M%S')

#Sort by date in ascending and price in descending order

sorted_date_price_df = df.sort_values(by=['date', 'price'], ascending=[True, False])

#Display top 5 results
print(sorted_date_price_df.head(5))

               id       date      price  bedrooms  bathrooms  sqft_living  \
312    1860600135 2014-05-02  2384000.0         5       2.50         3650   
4335   4217401055 2014-05-02  1400000.0         4       2.50         2920   
5043   4219400290 2014-05-02  1200000.0         5       2.75         2910   
17038  2326059099 2014-05-02   838000.0         4       2.50         3310   
17402  1868902745 2014-05-02   805000.0         3       2.00         2710   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
312        9050     2.0           0     4  ...     10        3370   
4335       4000     1.5           0     0  ...      8        1910   
5043       9480     1.5           0     0  ...      8        2910   
17038     42998     2.0           0     0  ...      9        3310   
17402      4500     1.5           0     0  ...      8        1880   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
312              280      1921             0   

In [124]:
#Sort the DataFrame based on the bedrooms column in ascending order and 
#then by bathrooms in descending order. 

sorted_bedroom_bathroom_df = df.sort_values(by=['bedrooms', 'bathrooms'], ascending=[True, False])

#Display the first 10 results.

print(sorted_bedroom_bathroom_df.head(10))

               id       date      price  bedrooms  bathrooms  sqft_living  \
8477   2569500210 2014-11-17   339950.0         0       2.50         2290   
8484   2310060040 2014-09-25   240000.0         0       2.50         1810   
12653  7849202299 2015-02-18   320000.0         0       2.50         1490   
3467   1453602309 2014-08-05   288000.0         0       1.50         1430   
4868   6896300380 2014-10-02   228000.0         0       1.00          390   
18379  1222029077 2014-10-29   265000.0         0       0.75          384   
875    6306400140 2014-06-12  1095000.0         0       0.00         3064   
3119   3918400017 2015-02-05   380000.0         0       0.00         1470   
6994   2954400190 2014-06-24  1295650.0         0       0.00         4810   
9773   3374500520 2015-04-29   355000.0         0       0.00         2460   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
8477       8319     2.0           0     0  ...      8        2290   
8484       566

In [125]:
#Filter and Sort: Filter the DataFrame to include only homes built after the year 2000. 
#Then, sort this filtered data by square feet in descending order and display the top 5 largest homes built 
#after the year 2000.

#Establish another dataframe equal to the prior dataframe that meets the specified criteria
#Define criteria

min_yr_built = 2000

#Establish new dataframe that meets criteria
filtered_df = df[(df['yr_built'] > min_yr_built)]

#Establish a sorted dataframe based on the dataframe that meets the criteria
sorted_sqft_post2000_df = filtered_df.sort_values(by=['sqft_lot'], ascending=[False])

#Print the top 5 results
print(sorted_sqft_post2000_df.head(5))

               id       date      price  bedrooms  bathrooms  sqft_living  \
7769   2323089009 2015-01-19   855000.0         4       3.50         4030   
4441   3626079040 2014-07-30   790000.0         2       3.00         2560   
6691   2624089007 2015-03-20  1998000.0         2       2.50         3900   
7077   2724079090 2015-01-05  1650000.0         4       3.25         3920   
20452  1125079111 2015-04-15  1600000.0         4       5.50         6530   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
7769    1024068     2.0           0     0  ...     10        4030   
4441     982278     1.0           0     0  ...      8        2560   
6691     920423     2.0           0     0  ...     12        3900   
7077     881654     3.0           0     3  ...     11        3920   
20452    871200     2.0           0     2  ...     11        6530   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
7769               0      2006             0   

In [126]:
#Practice Problem 6:
#Continuing with your home sales DataFrame, you need to further analyze specific portions of the dataset 
#using Pandas indexing to answer several queries.
#Task:
#Retrieve Specific Columns: Retrieve and display the price, year built, and square feet columns for the first 15 rows
#in the DataFrame.
#Locate by Index: Use .loc to display all the details of the 100th to 110th home sales in the DataFrame.
#Conditional Indexing: Use boolean indexing to find and display all home sales where the price is greater than $500,000,
#and the home has more than 3 bedrooms.
#Date Range Indexing: Filter and display all home sales that occurred during the month of May. 
#Assume the date column is in 'YYYY-MM-DD' format.
#Setting Values with Indexing: For the home sales with more than 4 bedrooms, set the price to be increased by 10%.
#Ensure that this change is reflected in the original DataFrame.

In [127]:
#Define columns of interest
price_yrbuilt_sqft = ['price','yr_built','sqft_lot']
start_row = 1
end_row = 15

#View results
print('The price, year built, and lot square footage of the first 15 homes are:\n')
print(df.loc[start_row:end_row, price_yrbuilt_sqft])

The price, year built, and lot square footage of the first 15 homes are:

        price  yr_built  sqft_lot
1    538000.0      1951      7242
2    180000.0      1933     10000
3    604000.0      1965      5000
4    510000.0      1987      8080
5   1225000.0      2001    101930
6    257500.0      1995      6819
7    291850.0      1963      9711
8    229500.0      1960      7470
9    323000.0      2003      6560
10   662500.0      1965      9796
11   468000.0      1942      6000
12   310000.0      1927     19901
13   400000.0      1977      9680
14   530000.0      1900      4850
15   650000.0      1979      5000


In [128]:
#Use .loc to diplay all the details for 100th and 110th home sales
#Note we need to use double brackets to keep Python from thinking the second value is a column
print(df.loc[[100,110]])

             id       date     price  bedrooms  bathrooms  sqft_living  \
100  1952200240 2014-06-11  850830.0         3        2.5         2070   
110  9545230140 2014-07-25  597750.0         4        2.5         2310   

     sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
100     13241     1.5           0     0  ...      9        1270   
110      9624     2.0           0     0  ...      8        2310   

     sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
100            800      1910             0    98102  47.6415 -122.315   
110              0      1984             0    98027  47.5386 -122.053   

     sqft_living15  sqft_lot15  
100           2200        4500  
110           1940        9636  

[2 rows x 21 columns]


In [129]:
#Display all home sales where the price is greater than $500,000,
#and the home has more than 3 bedrooms.
filtered_df = df.loc[(df['price'] > 500000) & (df['bedrooms'] > 3)]

# Display the resulting dataframe
print(filtered_df)

               id       date      price  bedrooms  bathrooms  sqft_living  \
3      2487200875 2014-12-09   604000.0         4       3.00         1960   
5      7237550310 2014-05-12  1225000.0         4       4.50         5420   
14     1175000570 2015-03-12   530000.0         5       2.00         1810   
15     9297300055 2015-01-24   650000.0         4       3.00         2950   
29     1873100390 2015-03-02   719000.0         4       2.50         2570   
...           ...        ...        ...       ...        ...          ...   
21598  8956200760 2014-10-13   541800.0         4       2.50         3118   
21599  7202300110 2014-09-15   810000.0         4       3.00         3990   
21600   249000205 2014-10-15  1537000.0         5       3.75         4470   
21605  3448900210 2014-10-14   610685.0         4       2.50         2520   
21606  7936000429 2015-03-26  1007500.0         4       3.50         3510   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
3     

In [130]:
#Display all home sales that occurred during the month of May. 

may_sales_df = df[df['date'].dt.month == 5]
print(may_sales_df)

               id       date      price  bedrooms  bathrooms  sqft_living  \
5      7237550310 2014-05-12  1225000.0         4       4.50         5420   
11     9212900260 2014-05-27   468000.0         2       1.00         1160   
12      114101516 2014-05-28   310000.0         3       1.00         1430   
17     6865200140 2014-05-29   485000.0         4       1.00         1600   
20     6300500875 2014-05-14   385000.0         4       1.75         1620   
...           ...        ...        ...       ...        ...          ...   
21574  1931300090 2014-05-07   610950.0         3       3.00         1680   
21579  7011201004 2014-05-29   645000.0         3       3.25         1730   
21581  7853420110 2015-05-04   625000.0         3       3.00         2780   
21590  7430200100 2014-05-14  1222500.0         4       3.50         4910   
21608   263000018 2014-05-21   360000.0         3       2.50         1530   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
5     

In [131]:
#For the home sales with more than 4 bedrooms, set the price to be increased by 10%.
#Ensure that this change is reflected in the original DataFrame.

#Let's view the current prices of homes with four bedrooms

print(df.loc[df['bedrooms'] > 4])


               id       date      price  bedrooms  bathrooms  sqft_living  \
14     1175000570 2015-03-12   530000.0         5       2.00         1810   
22     7137970340 2014-07-03   285000.0         5       2.50         2270   
42     7203220400 2014-07-07   861990.0         5       2.75         3595   
51     7231300125 2015-02-17   345000.0         5       2.50         3150   
54     4217401195 2015-03-03   920000.0         5       2.25         2730   
...           ...        ...        ...       ...        ...          ...   
21564  7168100015 2014-10-09   579950.0         5       2.75         3080   
21576  9253900271 2015-01-07  3567000.0         5       4.50         4850   
21593  8672200110 2015-03-17  1088000.0         5       3.75         4170   
21596  7502800100 2014-08-13   679950.0         5       2.75         3600   
21600   249000205 2014-10-15  1537000.0         5       3.75         4470   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
14    

In [132]:
#Note homesale ID 14 has a price of $530K. Homesale ID 22 is $285K.

#Identify homes with more than 4 bedrooms. Then take the corresponding price, and multiply by 110%.
df.loc[df['bedrooms'] > 4, 'price'] *= 1.10

#Show new results

print(df.loc[df['bedrooms'] > 4])

               id       date      price  bedrooms  bathrooms  sqft_living  \
14     1175000570 2015-03-12   583000.0         5       2.00         1810   
22     7137970340 2014-07-03   313500.0         5       2.50         2270   
42     7203220400 2014-07-07   948189.0         5       2.75         3595   
51     7231300125 2015-02-17   379500.0         5       2.50         3150   
54     4217401195 2015-03-03  1012000.0         5       2.25         2730   
...           ...        ...        ...       ...        ...          ...   
21564  7168100015 2014-10-09   637945.0         5       2.75         3080   
21576  9253900271 2015-01-07  3923700.0         5       4.50         4850   
21593  8672200110 2015-03-17  1196800.0         5       3.75         4170   
21596  7502800100 2014-08-13   747945.0         5       2.75         3600   
21600   249000205 2014-10-15  1690700.0         5       3.75         4470   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
14    

In [133]:
#The price of homesale ID 14 and homesale ID 22 have increased by 10%.

In [134]:
#Practice Problem 7:
#With your home sales DataFrame, you are tasked with analyzing the dataset to understand the central tendencies
#and spread of specific variables. This will help in gaining insights into the general landscape of home sales in the dataset.
#Task:
#Price Analysis:
#Calculate and display the mean, median, mode, and standard deviation of the price column.
#Identify and display the highest and lowest price in the dataset.
#Square Feet Analysis:
#Calculate and display the mean, median, mode, and standard deviation of the square feet column.
#Identify and display the largest and smallest home in terms of square footage.
#Year Built Analysis:
#Calculate and display the mean, median, and mode of the year built column.
#Identify and display the oldest and newest home in the dataset.
#Bedrooms and Bathrooms Analysis:
#Calculate and display the average number of bedrooms and bathrooms in the dataset.
#Identify and display the home with the most bedrooms and the home with the most bathrooms.
#Price Per Square Foot:
#Create a new column price per square foot in the DataFrame.
#Calculate and display the mean, median, mode, and standard deviation of this new column.

In [135]:
#Price, sqft, and year built analysis
#Run a loop on a list to calculate summary statistics for three variables of interest
#Use the mean, median, mode, std, min, and max functions to calculate and print summary statistics.

variables = ['price','sqft_lot','yr_built']

for var in variables :
    mean = df[var].mean()
    median = df[var].median()
    mode = df[var].mode()
    std_dev = df[var].std()
    minimum=df[var].min()
    maximum=df[var].max()
    print("Variable name:",var)
    print("Mean:", mean)
    print("Median:", median)
    print("Mode:", mode)
    print("Standard Deviation:", std_dev)
    print("Minimum:", minimum)
    print("Maximum:", maximum)
    print("\n")



Variable name: price
Mean: 547229.1261509277
Median: 452500.0
Mode: 0    350000.0
Name: price, dtype: float64
Standard Deviation: 382770.2309329748
Minimum: 75000.0
Maximum: 8470000.0


Variable name: sqft_lot
Mean: 15106.967565816869
Median: 7618.0
Mode: 0    5000
Name: sqft_lot, dtype: int64
Standard Deviation: 41420.51151513528
Minimum: 520
Maximum: 1651359


Variable name: yr_built
Mean: 1971.0051357978994
Median: 1975.0
Mode: 0    2014
Name: yr_built, dtype: int64
Standard Deviation: 29.373410802390172
Minimum: 1900
Maximum: 2015




In [136]:
#Identify and display the largest and smallest homes.
#Identify and display the oldest and newst home in the dataset.
#Identify and display the home with the most bedrooms and the home with the most bathrooms.

print('Home(s) with the most square footage lot:')

#Display data for homes with the square footage equal to the maximum square footage:
print(df.loc[df['sqft_lot'] == df['sqft_lot'].max()])
print('\n')

print('Home(s) with the least square footage lot:')

#Display data for homes with the square footage equal to the maximum square footage:
print(df.loc[df['sqft_lot'] == df['sqft_lot'].min()])
print('\n')

print('Oldest home(s):')

#Display data for homes with the square footage equal to the maximum square footage:
print(df.loc[df['yr_built'] == df['yr_built'].min()])
print('\n')

print('Newest home(s):')

#Display data for homes with the square footage equal to the maximum square footage:
print(df.loc[df['yr_built'] == df['yr_built'].max()])
print('\n')

print('Home(s) with the most bedrooms:')

#Display data for homes with the most bedrooms:
print(df.loc[df['bedrooms'] == df['bedrooms'].max()])
print('\n')

print('Home(s) with the most bathrooms:')

#Display data for homes with the most bedrooms:
print(df.loc[df['bathrooms'] == df['bathrooms'].max()])
print('\n')


Home(s) with the most square footage lot:
              id       date     price  bedrooms  bathrooms  sqft_living  \
1719  1020069017 2015-03-27  700000.0         4        1.0         1300   

      sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
1719   1651359     1.0           0     3  ...      6        1300   

      sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
1719              0      1920             0    98022  47.2313 -122.023   

      sqft_living15  sqft_lot15  
1719           2560      425581  

[1 rows x 21 columns]


Home(s) with the least square footage lot:
               id       date     price  bedrooms  bathrooms  sqft_living  \
15743  9828702895 2014-10-22  700000.0         4       1.75         2420   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
15743       520     1.5           0     0  ...      7        2420   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
15743             

In [137]:
#Create new price per square foot column

df['price_sqft'] = df['price'] / df['sqft_lot']

#Print summary statistics
variables = ['price_sqft']

for var in variables :
    mean = df[var].mean()
    median = df[var].median()
    mode = df[var].mode()
    std_dev = df[var].std()
    minimum=df[var].min()
    maximum=df[var].max()
    print("Variable name:",var)
    print("Mean:", mean)
    print("Median:", median)
    print("Mode:", mode)
    print("Standard Deviation:", std_dev)
    print("Minimum:", minimum)
    print("Maximum:", maximum)
    print("\n")


Variable name: price_sqft
Mean: 89.76794018534879
Median: 59.774964838255976
Mode: 0    100.0
Name: price_sqft, dtype: float64
Standard Deviation: 94.58500309033185
Minimum: 0.16311897211008985
Maximum: 2027.208538587849




In [138]:
#I think I have enough practice problems to cover my bases for the material this week, but just to be sure I'm going
#to write my own practice problem to use some of the exploratory data analysis functions from the last module lesson.
#Practice Problem 8: Experiment with the describe, unique, groupby, and tabulation commands to do some data quality checks.

#Let's summarize our variables to get a sense of the distribution of each. There should be 21.
display(df.describe())

id         price      bedrooms     bathrooms   sqft_living  \
count  2.161300e+04  2.161300e+04  21613.000000  21613.000000  21613.000000   
mean   4.580302e+09  5.472291e+05      3.370842      2.114757   2079.899736   
std    2.876566e+09  3.827702e+05      0.930062      0.770163    918.440897   
min    1.000102e+06  7.500000e+04      0.000000      0.000000    290.000000   
25%    2.123049e+09  3.249500e+05      3.000000      1.750000   1427.000000   
50%    3.904930e+09  4.525000e+05      3.000000      2.250000   1910.000000   
75%    7.308900e+09  6.500000e+05      4.000000      2.500000   2550.000000   
max    9.900000e+09  8.470000e+06     33.000000      8.000000  13540.000000   

           sqft_lot        floors    waterfront          view     condition  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  21613.000000   
mean   1.510697e+04      1.494309      0.007542      0.234303      3.409430   
std    4.142051e+04      0.539989      0.086517      0.766318      0.650743   
min    5.200000e+02      1.000000      0.000000      0.000000      1.000000   
25%    5.040000e+03      1.000000      0.000000      0.000000      3.000000   
50%    7.618000e+03      1.500000      0.000000      0.000000      3.000000   
75%    1.068800e+04      2.000000      0.000000      0.000000      4.000000   
max    1.651359e+06      3.500000      1.000000      4.000000      5.000000   

       ...    sqft_above  sqft_basement      yr_built  yr_renovated  \
count  ...  21613.000000   21613.000000  21613.000000  21613.000000   
mean   ...   1788.390691     291.509045   1971.005136     84.402258   
std    ...    828.090978     442.575043     29.373411    401.679240   
min    ...    290.000000       0.000000   1900.000000      0.000000   
25%    ...   1190.000000       0.000000   1951.000000      0.000000   
50%    ...   1560.000000       0.000000   1975.000000      0.000000   
75%    ...   2210.000000     560.000000   1997.000000      0.000000   
max    ...   9410.000000    4820.000000   2015.000000   2015.000000   

            zipcode           lat          long  sqft_living15     sqft_lot15  \
count  21613.000000  21613.000000  21613.000000   21613.000000   21613.000000   
mean   98077.939805     47.560053   -122.213896    1986.552492   12768.455652   
std       53.505026      0.138564      0.140828     685.391304   27304.179631   
min    98001.000000     47.155900   -122.519000     399.000000     651.000000   
25%    98033.000000     47.471000   -122.328000    1490.000000    5100.000000   
50%    98065.000000     47.571800   -122.230000    1840.000000    7620.000000   
75%    98118.000000     47.678000   -122.125000    2360.000000   10083.000000   
max    98199.000000     47.777600   -121.315000    6210.000000  871200.000000   

         price_sqft  
count  21613.000000  
mean      89.767940  
std       94.585003  
min        0.163119  
25%       33.529351  
50%       59.774965  
75%      108.877005  
max     2027.208539  

[8 rows x 21 columns]

In [139]:
#Looking at the descriptions, the variables I am interested in the unique values of are:
#Waterfront - is it truly binary?
#Floors, bedrooms, bathrooms - are there any interesting fractions here?

variables = ['waterfront','floors','bedrooms','bathrooms']

for var in variables :
    print(var,'Unique values:')
    print(df[var].unique())
    print('\n')

waterfront Unique values:
[0 1]


floors Unique values:
[1.  2.  1.5 3.  2.5 3.5]


bedrooms Unique values:
[ 3  2  4  5  1  6  7  0  8  9 11 10 33]


bathrooms Unique values:
[1.   2.25 3.   2.   4.5  1.5  2.5  1.75 2.75 3.25 4.   3.5  0.75 4.75
 5.   4.25 3.75 0.   1.25 5.25 6.   0.5  5.5  6.75 5.75 8.   7.5  7.75
 6.25 6.5 ]




In [140]:
#Interesting. We know waterfront is a binary variable. Bedrooms are integer values, where
#bathrooms and floors are float values.
#Let's use the groupby command to get a sense of how much more waterfront homes go for.

#Calculate average sales for with/out waterfront
avg_price = df.groupby('waterfront')['price'].mean()

#Reformat for more readability using lambda
avg_price_formatted = avg_price.apply(lambda x: '{:,.2f}'.format(x))

# Print out the results
print("Average Price, With/Without Waterfront")
display(avg_price_formatted)

Average Price, With/Without Waterfront


waterfront
0      538,458.31
1    1,701,425.87
Name: price, dtype: object

In [141]:
#Looks like on average, a waterfront home sells for about three times as much as one without waterfront.
#Finally, lets use crosstab to view the relationship between bedrooms and floors.

#Creating a bedroom / floor crosstab
tab = pd.crosstab(
    index=df['bedrooms'],
    columns=df['floors'],
)

display(tab)  

floors     1.0  1.5   2.0  2.5  3.0  3.5
bedrooms                                
0            4    0     6    0    2    1
1          162   21    12    1    3    0
2         1951  182   497    5  123    2
3         5455  786  3118   56  405    4
4         2383  698  3682   58   61    0
5          605  185   775   23   13    0
6          104   30   119   14    5    0
7            9    7    19    2    1    0
8            5    1     6    0    0    1
9            0    0     4    2    0    0
10           1    0     2    0    0    0
11           0    0     1    0    0    0
33           1    0     0    0    0    0